services:
  postgres:
    image: postgres:16
    container_name: neoxmeet-postgres
    environment:
      POSTGRES_USER: neoxmeet
      POSTGRES_PASSWORD: neoxmeetpass
      POSTGRES_DB: neoxmeet
    ports:
      - "5432:5432"
    volumes:
      - neoxmeet_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: neoxmeet-redis
    ports:
      - "6379:6379"

volumes:
  neoxmeet_pgdata:
